### ISSUE TITLE
The Perplexity Search Window Remains Gray in 3.0

### ISSUE THREAD

**Issue by Akusho** [inulute/perplexity-ai-app#19] opened 2024-11-04 11:22 UTC
Hello,
I'm on Windows 11. I've updated to the 3.0 version, and now the default startup section with Perplexity Search (not Chat) remains gray on launch. I can hit ctrl+R, and it will flash with my Perplexity library for a second, but then will go back to gray screen again.  The chat works.
Downgraded to 2.2 and the issue has fixed itself.
I tried updating to 3.0 from 2.2, or removing the 3.0 and reinstalling from scratch. Same behavior.

**Comment by inulute** [comment] 2024-11-04 12:23
Thank you for bringing this to our attention. We'll investigate the matter.

**Comment by Norman-else** [comment] 2024-11-04 13:59
The same on my windows:
![image](https://github.com/user-attachments/assets/1e6a435b-cd7f-4b7c-a7ba-8b0989631f74)

**Comment by joelnale** [comment] 2024-11-04 14:04
I'm experiencing this same issue.  I installed 3.0 directly for the first time and also removed, then installed 2.2 (which worked) then installed 3.0 once again, experiencing the same gray screen.
![image](https://github.com/user-attachments/assets/a5921df2-fae1-4772-a7bc-04d0932baab1)

**Comment by inulute** [comment] 2024-11-04 14:04
Hey guys, Hi everyone, please send me a direct message on Telegram at [inulute](https://t.me/inulute) so I can share test builds with you. Thanks!

**Comment by inulute** [comment] 2024-11-04 14:24
Could you please try downloading and installing the provided file package from this link: https://filetransfer.io/data-package/01Wkqloq#link? 

If the issue persists, feel free to let us know so we can further investigate. Thank you for your patience, and we look forward to resolving this for you!

**Comment by Norman-else** [comment] 2024-11-04 14:25
Trying

**Comment by Norman-else** [comment] 2024-11-04 14:28
it seems like still experience the issue. After I installed the file you sent above, nothing can works well now. lol.

**Comment by joelnale** [comment] 2024-11-04 14:31
I overinstalled the new package you sent above and it works for me.

**Comment by inulute** [comment] 2024-11-04 14:33
> it seems like still experience the issue. After I installed the file you sent above, nothing can works well now. lol.

Try a clean install to see if that helps.

**Comment by Norman-else** [comment] 2024-11-04 14:34
Works now after I uninstall the app and install again.

**Closed** 2024-11-04 14:52 UTC

**Comment by Akusho** [comment] 2024-11-04 15:32
Hi, 
Glad that you have found a fix that worked for other people with the same issue.
Could you please share the file again? The link has expired, and I wasn't quick enough to download it.

**Comment by inulute** [comment] 2024-11-04 16:13
> Hi, 
> Glad that you have found a fix that worked for other people with the same issue.
> Could you please share the file again? The link has expired, and I wasn't quick enough to download it.

Hey, we'll be releasing HOTFIX soon. Thanks!!

**Comment by inulute** [comment] 2024-11-04 18:35
**Startup Issue Fixed in v3.1.0**

We sincerely apologize for the inconvenience caused by the **startup issue** where the Perplexity Search screen appeared gray on launch. We know how important a smooth experience is, and we’re truly sorry for any disruption this may have caused in your workflow.

We’re pleased to let you know this issue has been resolved in **v3.1.0**. The updated version is now available for download, and we recommend a clean install for the best experience. Thank you so much for your patience and invaluable feedback!

**[Download Perplexity AI v3.1.0](https://www.pling.com/p/2107698/)**
